name: Test pull request
on: pull_request

jobs:
  run-terraform-tests:
    name: Run Terraform tests
    uses: logikal-io/github-workflows/.github/workflows/terraform-run-tests.yml@v11
    with:
      terragrunt-dir: .
