name: Test pull request
on: pull_request

jobs:
  run-terraform-tests:
    name: Run Terraform tests
    uses: logikal-io/github-workflows/.github/workflows/run-terraform-tests.yml@v5
    with:
      root-dir: .
